[package]
name = "rust-log-parser"
version = "0.1.0"
edition = "2021"
authors = ["Mark A. Hershberger <mah@nichework.com>"]

[dependencies]
regex = "1.7.0"
itertools = "0.10.5"
structopt = "0.3.26"
serde_json = "1.0.87"
serde = { version = "1.0.147", features = ["derive"] }
